export const characteristicConstants = {
    CREATE_REQUEST: 'CHARACTERISTICS_CREATE_REQUEST',
    CREATE_SUCCESS: 'CHARACTERISTICS_CREATE_SUCCESS',
    CREATE_FAILURE: 'CHARACTERISTICS_CREATE_FAILURE',

    UPDATE_REQUEST: 'CHARACTERISTICS_UPDATE_REQUEST',
    UPDATE_SUCCESS: 'CHARACTERISTICS_UPDATE_SUCCESS',
    UPDATE_FAILURE: 'CHARACTERISTICS_UPDATE_FAILURE',

    GETONE_REQUEST: 'CHARACTERISTICS_GETONE_REQUEST',
    GETONE_SUCCESS: 'CHARACTERISTICS_GETONE_SUCCESS',
    GETONE_FAILURE: 'CHARACTERISTICS_GETONE_FAILURE',

    GETALL_REQUEST: 'CHARACTERISTICS_GETALL_REQUEST',
    GETALL_SUCCESS: 'CHARACTERISTICS_GETALL_SUCCESS',
    GETALL_FAILURE: 'CHARACTERISTICS_GETALL_FAILURE',

    DELETE_REQUEST: 'CHARACTERISTICS_DELETE_REQUEST',
    DELETE_SUCCESS: 'CHARACTERISTICS_DELETE_SUCCESS',
    DELETE_FAILURE: 'CHARACTERISTICS_DELETE_FAILURE'    
};
