export const configConstants = {
    SETTYPE_REQUEST: 'CONFIGS_SETTYPE_REQUEST',
    SETTYPE_SUCCESS: 'CONFIGS_SETTYPE_SUCCESS',
    SETTYPE_FAILURE: 'CONFIGS_SETTYPE_FAILURE',

    GETALL_REQUEST: 'CONFIGS_GETALL_REQUEST',
    GETALL_SUCCESS: 'CONFIGS_GETALL_SUCCESS',
    GETALL_FAILURE: 'CONFIGS_GETALL_FAILURE',
};
