export const dimensionConstants = {

    GETONE_REQUEST: 'DIMENSIONS_GETONE_REQUEST',
    GETONE_SUCCESS: 'DIMENSIONS_GETONE_SUCCESS',
    GETONE_FAILURE: 'DIMENSIONS_GETONE_FAILURE',

    GETALL_REQUEST: 'DIMENSIONS_GETALL_REQUEST',
    GETALL_SUCCESS: 'DIMENSIONS_GETALL_SUCCESS',
    GETALL_FAILURE: 'DIMENSIONS_GETALL_FAILURE',
};
