export const projectConstants = {
    CREATE_REQUEST: 'PROJECTS_CREATE_REQUEST',
    CREATE_SUCCESS: 'PROJECTS_CREATE_SUCCESS',
    CREATE_FAILURE: 'PROJECTS_CREATE_FAILURE',

    UPDATE_REQUEST: 'PROJECTS_UPDATE_REQUEST',
    UPDATE_SUCCESS: 'PROJECTS_UPDATE_SUCCESS',
    UPDATE_FAILURE: 'PROJECTS_UPDATE_FAILURE',

    GETONE_REQUEST: 'PROJECTS_GETONE_REQUEST',
    GETONE_SUCCESS: 'PROJECTS_GETONE_SUCCESS',
    GETONE_FAILURE: 'PROJECTS_GETONE_FAILURE',

    GETALL_REQUEST: 'PROJECTS_GETALL_REQUEST',
    GETALL_SUCCESS: 'PROJECTS_GETALL_SUCCESS',
    GETALL_FAILURE: 'PROJECTS_GETALL_FAILURE',

    DELETE_REQUEST: 'PROJECTS_DELETE_REQUEST',
    DELETE_SUCCESS: 'PROJECTS_DELETE_SUCCESS',
    DELETE_FAILURE: 'PROJECTS_DELETE_FAILURE',

    SAVEMC_REQUEST: 'SAVEMC_PROJECTS_REQUEST',
    SAVEMC_SUCCESS: 'SAVEMC_PROJECTS_SUCCESS',
    SAVEMC_FAILURE: 'SAVEMC_PROJECTS_FAILURE'    
};
