export const tenantSettingsConstants = {
    GETALL_REQUEST: 'TENANT_SETTINGS_GETALL_REQUEST',
    GETALL_SUCCESS: 'TENANT_SETTINGS_GETALL_SUCCESS',
    GETALL_FAILURE: 'TENANT_SETTINGS_GETALL_FAILURE',

    GETALLTYPES_REQUEST: 'TENANT_SETTINGS_GETALLTYPES_REQUEST',
    GETALLTYPES_SUCCESS: 'TENANT_SETTINGS_GETALLTYPES_SUCCESS',
    GETALLTYPES_FAILURE: 'TENANT_SETTINGS_GETALLTYPES_FAILURE',

    GETBYTYPE_REQUEST: 'TENANT_SETTINGS_GETBYTYPE_REQUEST',
    GETBYTYPE_SUCCESS: 'TENANT_SETTINGS_GETBYTYPE_SUCCESS',
    GETBYTYPE_FAILURE: 'TENANT_SETTINGS_GETBYTYPE_FAILURE',

    
};
