const INDUSTRIES = [
  { name: "Accounting", id: "accounting" },
  { name: "Airlines/Aviation", id: "airlines-aviation" },
  {
    name: "Alternative Dispute Resolution",
    id: "alternative-dispute-resolution"
  },
  { name: "Alternative Medicine", id: "alternative-medicine" },
  { name: "Animation", id: "animation" },
  { name: "Apparel and Fashion", id: "apparel-and-fashion" },
  { name: "Architecture and Planning", id: "architecture-and-planning" },
  { name: "Arts and Crafts", id: "arts-and-crafts" },
  { name: "Automotive", id: "automotive" },
  { name: "Aviation and Aerospace", id: "aviation-and-aerospace" },
  { name: "Banking", id: "banking" },
  { name: "Biotechnology", id: "biotechnology" },
  { name: "Broadcast Media", id: "broadcast-media" },
  { name: "Building Materials", id: "building-materials" },
  {
    name: "Business Supplies and Equipment",
    id: "business-supplies-and-equipment"
  },
  { name: "Capital Markets", id: "capital-markets" },
  { name: "Chemicals", id: "chemicals" },
  {
    name: "Civic and Social Organization",
    id: "civic-and-social-organization"
  },
  { name: "Civil Engineering", id: "civil-engineering" },
  { name: "Commercial Real Estate", id: "commercial-real-estate" },
  {
    name: "Computer and Network Security",
    id: "computer-and-network-security"
  },
  { name: "Computer Games", id: "computer-games" },
  { name: "Computer Hardware", id: "computer-hardware" },
  { name: "Computer Networking", id: "computer-networking" },
  { name: "Computer Software", id: "computer-software" },
  { name: "Construction", id: "construction" },
  { name: "Consumer Electronics", id: "consumer-electronics" },
  { name: "Consumer Goods", id: "consumer-goods" },
  { name: "Consumer Services", id: "consumer-services" },
  { name: "Cosmetics", id: "cosmetics" },
  { name: "Dairy", id: "dairy" },
  { name: "Defense and Space", id: "defense-and-space" },
  { name: "Design", id: "design" },
  { name: "Education Management", id: "education-management" },
  { name: "E-Learning", id: "e-learning" },
  {
    name: "Electrical/Electronic Manufacturing",
    id: "electrical-electronic-manufacturing"
  },
  { name: "Entertainment", id: "entertainment" },
  { name: "Environmental Services", id: "environmental-services" },
  { name: "Events Services", id: "events-services" },
  { name: "Executive Office", id: "executive-office" },
  { name: "Facilities Services", id: "facilities-services" },
  { name: "Farming", id: "farming" },
  { name: "Financial Services", id: "financial-services" },
  { name: "Fine Art", id: "fine-art" },
  { name: "Fishery", id: "fishery" },
  { name: "Food and Beverages", id: "food-and-beverages" },
  { name: "Food Production", id: "food-production" },
  { name: "Fund-Raising", id: "fund-raising" },
  { name: "Furniture", id: "furniture" },
  { name: "Gambling and Casinos", id: "gambling-and-casinos" },
  { name: "Glass, Ceramics and Concrete", id: "glass-ceramics-and-concrete" },
  { name: "Government Administration", id: "government-administration" },
  { name: "Government Relations", id: "government-relations" },
  { name: "Graphic Design", id: "graphic-design" },
  { name: "Health, Wellness and Fitness", id: "health-wellness-and-fitness" },
  { name: "Higher Education", id: "higher-education" },
  { name: "Hospital and Health Care", id: "hospital-and-health-care" },
  { name: "Hospitality", id: "hospitality" },
  { name: "Human Resources", id: "human-resources" },
  { name: "Import and Export", id: "import-and-export" },
  {
    name: "Individual and Family Services",
    id: "individual-and-family-services"
  },
  { name: "Industrial Automation", id: "industrial-automation" },
  { name: "Information Services", id: "information-services" },
  {
    name: "Information Technology and Services",
    id: "information-technology-and-services"
  },
  { name: "Insurance", id: "insurance" },
  { name: "International Affairs", id: "international-affairs" },
  {
    name: "International Trade and Development",
    id: "international-trade-and-development"
  },
  { name: "Internet", id: "internet" },
  { name: "Investment Banking", id: "investment-banking" },
  { name: "Investment Management", id: "investment-management" },
  { name: "Judiciary", id: "judiciary" },
  { name: "Law Enforcement", id: "law-enforcement" },
  { name: "Law Practice", id: "law-practice" },
  { name: "Legal Services", id: "legal-services" },
  { name: "Legislative Office", id: "legislative-office" },
  { name: "Leisure, Travel and Tourism", id: "leisure-travel-and-tourism" },
  { name: "Libraries", id: "libraries" },
  { name: "Logistics and Supply Chain", id: "logistics-and-supply-chain" },
  { name: "Luxury Goods and Jewelry", id: "luxury-goods-and-jewelry" },
  { name: "Machinery", id: "machinery" },
  { name: "Management Consulting", id: "management-consulting" },
  { name: "Maritime", id: "maritime" },
  { name: "Market Research", id: "market-research" },
  { name: "Marketing and Advertising", id: "marketing-and-advertising" },
  {
    name: "Mechanical or Industrial Engineering",
    id: "mechanical-or-industrial-engineering"
  },
  { name: "Media Production", id: "media-production" },
  { name: "Medical Devices", id: "medical-devices" },
  { name: "Medical Practice", id: "medical-practice" },
  { name: "Mental Health Care", id: "mental-health-care" },
  { name: "Military", id: "military" },
  { name: "Mining and Metals", id: "mining-and-metals" },
  { name: "Motion Pictures and Film", id: "motion-pictures-and-film" },
  { name: "Museums and Institutions", id: "museums-and-institutions" },
  { name: "Music", id: "music" },
  { name: "Nanotechnology", id: "nanotechnology" },
  { name: "Newspapers", id: "newspapers" },
  {
    name: "Non-Profit Organization Management",
    id: "non-profit-organization-management"
  },
  { name: "Oil and Energy", id: "oil-and-energy" },
  { name: "Online Media", id: "online-media" },
  { name: "Outsourcing/Offshoring", id: "outsourcing-offshoring" },
  { name: "Package/Freight Delivery", id: "package-freight-delivery" },
  { name: "Packaging and Containers", id: "packaging-and-containers" },
  { name: "Paper and Forest Products", id: "paper-and-forest-products" },
  { name: "Performing Arts", id: "performing-arts" },
  { name: "Pharmaceuticals", id: "pharmaceuticals" },
  { name: "Philanthropy", id: "philanthropy" },
  { name: "Photography", id: "photography" },
  { name: "Plastics", id: "plastics" },
  { name: "Political Organization", id: "political-organization" },
  { name: "Primary/Secondary Education", id: "primary-secondary-education" },
  { name: "Printing", id: "printing" },
  {
    name: "Professional Training and Coaching",
    id: "professional-training-and-coaching"
  },
  { name: "Program Development", id: "program-development" },
  { name: "Public Policy", id: "public-policy" },
  {
    name: "Public Relations and Communications",
    id: "public-relations-and-communications"
  },
  { name: "Public Safety", id: "public-safety" },
  { name: "Publishing", id: "publishing" },
  { name: "Railroad Manufacture", id: "railroad-manufacture" },
  { name: "Ranching", id: "ranching" },
  { name: "Real Estate", id: "real-estate" },
  {
    name: "Recreational Facilities and Services",
    id: "recreational-facilities-and-services"
  },
  { name: "Religious Institutions", id: "religious-institutions" },
  { name: "Renewables and Environment", id: "renewables-and-environment" },
  { name: "Research", id: "research" },
  { name: "Restaurants", id: "restaurants" },
  { name: "Retail", id: "retail" },
  { name: "Security and Investigations", id: "security-and-investigations" },
  { name: "Semiconductors", id: "semiconductors" },
  { name: "Shipbuilding", id: "shipbuilding" },
  { name: "Sporting Goods", id: "sporting-goods" },
  { name: "Sports", id: "sports" },
  { name: "Staffing and Recruiting", id: "staffing-and-recruiting" },
  { name: "Supermarkets", id: "supermarkets" },
  { name: "Telecommunications", id: "telecommunications" },
  { name: "Textiles", id: "textiles" },
  { name: "Think Tanks", id: "think-tanks" },
  { name: "Tobacco", id: "tobacco" },
  { name: "Translation and Localization", id: "translation-and-localization" },
  {
    name: "Transportation/Trucking/Railroad",
    id: "transportation-trucking-railroad"
  },
  { name: "Utilities", id: "utilities" },
  {
    name: "Venture Capital and Private Equity",
    id: "venture-capital-and-private-equity"
  },
  { name: "Veterinary", id: "veterinary" },
  { name: "Warehousing", id: "warehousing" },
  { name: "Wholesale", id: "wholesale" },
  { name: "Wine and Spirits", id: "wine-and-spirits" },
  { name: "Wireless", id: "wireless" },
  { name: "Writing and Editing", id: "writing-and-editing" }
];
module.exports = INDUSTRIES;
